language: android
jdk: oraclejdk7
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools

    - build-tools-24.0.0
    - android-24

    - extra-android-m2repository
    - extra-google-m2repository

    - sys-img-x86-android-24