language: android
jdk: oraclejdk8
android:
  components:
    - tools

    - build-tools-24.0.0
    - android-24

    - extra-android-m2repository
    - extra-google-m2repository

    - sys-img-x86_64-android-24

before_script:
  - echo no | android create avd --force -n test -t android-24 --abi x86_64
  - emulator -avd test -no-skin -no-audio -no-window  -qemu -enable-kvm &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &